<?php

namespace OVE\AuthentificationBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * parametresauthRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class parametresauthRepository extends EntityRepository
{
}
