security:
    encoders:
        OVE\AuthentificationBundle\User\LdapUser: plaintext
        Symfony\Component\Security\Core\User\User: plaintext


    providers:
        multiples:
            chain:
                providers: [in_memory,ldap]
        ldap:
            id: ove_authentification.security.user.provider
        in_memory:
            memory:
                users:
                    user:         { password: oveuserpass,    roles: [ 'ROLE_USER' ] }
                    admin:        { password: oveadminpass,   roles: [ 'ROLE_ADMIN', 'ROLE_PARAM' ] }


    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern: ^/
            anonymous: ~
            ove_authentification:
                provider: multiples
            logout:
                path: logout
            form_login:
                login_path:  /login
                check_path:  /login_check
                default_target_path:            /
            access_denied_url: /forbidden



    access_control:
        - { path: ^/administration,    roles: ['ROLE_ADMIN'] }
        - { path: ^/administration/,   roles: ['ROLE_ADMIN'] }

        - { path: ^/parametrage    ,   roles: ['ROLE_ADMIN', 'ROLE_PARAM', 'ROLE_DIRECTEUR', 'ROLE_DELEGATION'] }
        - { path: ^/parametrage/   ,   roles: ['ROLE_ADMIN', 'ROLE_PARAM', 'ROLE_DIRECTEUR', 'ROLE_DELEGATION'] }

        - { path: ^/login          ,   roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/anonyme        ,   roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/webservice/    ,   roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/               ,   roles: IS_AUTHENTICATED_FULLY }







